name: Post JSON File to Tandem URLs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON to Temperature Sensor
        run: |
          curl -X POST "https://your-temperature-api-url.com" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON to Humidity Sensor
        run: |
          curl -X POST "https://your-humidity-api-url.com" \
               -H "Content-Type: application/json" \
               -d @stream.json
